/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_opencvtest_OpenCV */

#ifndef _Included_com_example_opencvtest_OpenCV
#define _Included_com_example_opencvtest_OpenCV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_opencvtest_OpenCV
 * Method:    setSourceImage
 * Signature: ([IIILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_opencvtest_OpenCV_setSourceImage
  (JNIEnv *, jobject, jintArray, jint, jint, jstring);

/*
 * Class:     com_example_opencvtest_OpenCV
 * Method:    getSourceImage
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_opencvtest_OpenCV_getSourceImage
  (JNIEnv *, jobject);

/*
 * Class:     com_example_opencvtest_OpenCV
 * Method:    extractSURFFeature
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_opencvtest_OpenCV_extractSURFFeature
  (JNIEnv *, jobject);

/*
 * Class:     com_example_opencvtest_OpenCV
 * Method:    findEdgesandCorners
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_opencvtest_OpenCV_findEdgesandCorners
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_opencvtest_OpenCV
 * Method:    getCornerpoints
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_opencvtest_OpenCV_getCornerpoints
  (JNIEnv *, jobject);

/*
 * Class:     com_example_opencvtest_OpenCV
 * Method:    FindFeatures
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_opencvtest_OpenCV_FindFeatures
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
